apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-network-policy
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: my-nginx # อนุญาตเฉพาะ Pod ที่มี label app: my-nginx
      ports:
        - protocol: TCP
          port: 5432
